apiVersion: v1
kind: Service
metadata:
  name: enterprise-system-145109-kpy2-service
spec:
  selector:
    app: enterprise-system-145109-kpy2
  ports:
  - port: 80
    targetPort: 8000
  type: ClusterIP
